[mypy]
exclude = (?x)(
    ^scripts/llama\.cpp-src/
    | ^\.venv
    | ^scripts/\.venv-
    | ^models/
    | ^models\.zip$
  )
explicit_package_bases = True

[mypy-onnxruntime.*]
ignore_missing_imports = True

[mypy-onnx.*]
ignore_missing_imports = True
